name: Avica

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 360
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          curl -L -A "Mozilla/5.0" -o Downloads.bat "URL_HERE" -OutFile "Download.bat"
          cmd /c Downloads.bat

      - name: Show Website
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
